export const RIGHTCLICK="RIGHTCLICK";
export const LEFTCLICK="LEFTCLICK";
export const TOPCLICK="TOPCLICK";
export const BOTTOMCLICK="BOTTOMCLICK";
export const ADDDATATOARRAYA="ADDDATATOARRAYA";
export const ADDDATATOARRAYB="ADDDATATOARRAYB";
